apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    stream {

      upstream vernemq {
        server mqtt-headless-service.default.svc.cluster.local:1883;
      }
      server {
        listen 8883 ssl;
        # TLS Configuration
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 2;

        # Run Lua script for SAN validation
        # preread_by_lua_file /etc/nginx/lua/validate_san_hazelcast.lua;

        # Forward the connection to VerneMQ
        proxy_pass 10.0.0.113:8884;
        proxy_protocol on;

        # Timeout settings
        proxy_timeout 300s;
      }
    }