apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mqtt
  labels:
    app: nginx-mqtt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mqtt
  template:
    metadata:
      labels:
        app: nginx-mqtt
    spec:
      containers:
      - name: nginx
        # image: openresty/openresty:jammy
        image: nginx:latest
        # image: fabiocicerchia/nginx-lua
        ports:
        - containerPort: 8883
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: lua-scripts
          mountPath: /etc/nginx/lua/validate_san_hazelcast.lua
          subPath: validate_san_hazelcast.lua
        - name: nginx-certificates
          mountPath: /etc/nginx/certs/            # 挂载到 /etc/nginx/certs/
          readOnly: true     
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: lua-scripts
        configMap:
          name: lua-scripts
      - name: nginx-certificates
        secret:
          secretName: nginx-certificates  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-mqtt-service
spec:
  selector:
    app: nginx-mqtt
  ports:
  - port: 8883          # NGINX container port
    targetPort: 8883     # Target port in the container
    nodePort: 32283      # NodePort for external access
    protocol: TCP
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-mqtt-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-mqtt
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50