{{- $root := . -}}
{{- with .Values.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vernemq.fullname" $root }}-certs
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" $root }}
    helm.sh/chart: {{ include "vernemq.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
  {{- with .secret }}
    {{- with .labels }}
    {{ toYaml . | nindent 4}}
    {{- end }}
    {{- with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ required "you need to specify certificates.cert" .cert }}
  tls.key: {{ required "you need to specify certificates.key" .key }}
  ca.crt: {{ required "you need to specify certificates.ca" .ca }}
{{- end -}}
