apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: empd
    port: 4369
  - name: metrics
    port: 8888
    targetPort: api
  - name: mqtt
    port: {{ .Values.service.mqtt.port }}
    targetPort: mqtt
  - name: mqtts
    port: {{ .Values.service.mqtts.port }}
    targetPort: mqtts
  - name: ws
    port: {{ .Values.service.ws.port }}
    targetPort: ws
  - name: wss
    port: {{ .Values.service.wss.port }}
    targetPort: wss
  {{- if .Values.headlessService.customPorts }}
  {{- range .Values.headlessService.customPorts }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
