domain:
  gooptim: "gooptim.us"   #url to access the frontend UI dashboard  
accept_eula: "yes"
# 其他配置项，例如资源限制、持久化设置等
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 8Gi
