apiVersion: v1
kind: Service
metadata:
  name: mqtt-vernemq-nginx-inner
  labels:
    app.kubernetes.io/name: vernemq-nginx
    app.kubernetes.io/instance: my-release-nginx
spec:
  type: ClusterIP  # 根据您的需求可以改为NodePort或LoadBalancer
  ports:
  - name: mqtt-ssl
    port: 8883
    targetPort: 8883
    protocol: TCP
  selector:
    app.kubernetes.io/name: vernemq-nginx
    app.kubernetes.io/instance: my-release-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-vernemq-nginx
  labels:
    app.kubernetes.io/name: vernemq-nginx
    app.kubernetes.io/instance: my-release-nginx
spec:
  type: NodePort
  ports:
    - port: 8883
      targetPort: mqtt
      nodePort: 30883  # 可选：指定特定的端口号
      name: mqtt
  selector:
    app.kubernetes.io/name: vernemq-nginx
    app.kubernetes.io/instance: my-release-nginx