apiVersion: v1
kind: Service
metadata:
  name: my-release-vernemq
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: mqtt
      name: mqtt
  selector:
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/instance: my-release
