---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-release-vernemq
  labels:
    app.kubernetes.io/name: vernemq
    helm.sh/chart: vernemq-2.0.1
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: mqtt-vernemq
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vernemq
      app.kubernetes.io/instance: my-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vernemq
        app.kubernetes.io/instance: my-release
    spec:
      serviceAccountName: my-release-vernemq
      securityContext:  
        fsGroup: 10000
        runAsGroup: 10000
        runAsUser: 10000
      containers:
      - name: vernemq
        image: vernemq/vernemq:latest
        ports:
        - name: mqtt
          containerPort: 1883
        env:
        - name: DOCKER_VERNEMQ_ACCEPT_EULA
          value: "yes"
        - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
          value: "on"
