version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx6
    ports:
      - "8883:8883"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ca/server.crt:/etc/nginx/crt/server.crt:ro
      - ./ca/server.key:/etc/nginx/crt/server.key:ro
      - ./ca/ca-client.crt:/etc/nginx/crt/ca.crt:ro
    user: root
    networks:
      - mqtt-network-1
    restart: unless-stopped

  vernemq:
    image: vernemq/vernemq
    container_name: vernemq6
    ports:
      - "1883:1883"
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    networks:
      - mqtt-network-1
    restart: unless-stopped

networks:
  mqtt-network-1:
    name: mqtt-network-1
    driver: bridge