---
# Source: vernemq/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-release-vernemq
  namespace: default
  labels:
    app.kubernetes.io/name: vernemq
    helm.sh/chart: vernemq-2.0.1
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
---
# Source: vernemq/templates/role.yaml
# VerneMQ needs to query k8s apiserver to list the other pods in the namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-release-vernemq
  namespace: default
  labels:
    app.kubernetes.io/name: vernemq
    helm.sh/chart: vernemq-2.0.1
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
---
# Source: vernemq/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-release-vernemq
  namespace: default
  labels:
    app.kubernetes.io/name: vernemq
    helm.sh/chart: vernemq-2.0.1
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: my-release-vernemq 
    namespace: default
roleRef:
  kind: Role 
  name: my-release-vernemq 
  apiGroup: rbac.authorization.k8s.io
---